### ISSUE TITLE
Certificate Upload Error

### ISSUE THREAD

**Issue by joeyboey** [franzs/fritzbox_upload_certificate#1]
First of all, thanks for the script!

Unfortunately I always get an error while uploading. Is there some command to further debug the response from the fritzbox?

Fritz!Box 6591 Cable
Fritz!OS 7.13

**Comment by franzs** [comment]
Hi Joey!
Sorry for the delayed answer.
At the moment there is no real debug mode. In general you have to have a look at the responses. An easy way would be to include a `| tee <output-file>` after `${CURL_CMD}`.

**Comment by joeyboey** [comment]
Thanks for your help, i will try to debug this further!
