### ISSUE TITLE
Too strict privkey check???

### ISSUE THREAD

**Issue by cxxcoder** [franzs/fritzbox_upload_certificate#21]
The private key is checked to have a "-BEGIN RSA PRIVATE KEY-" header.
However, the privkey.pem file generated by certbot has a "-BEGIN PRIVATE KEY-" header and is thus rejected by the script.
After commenting out the check the upload by the script to a FB7490 with latest FritzOS worked flawlessly and there was no SSL error when accessing the FB over the internet.
Perhaps this check should be adapted appropriately.

**Comment by franzs** [comment]
Thanks for opening this issue. Can you please test this code if it works for you?

https://github.com/franzs/fritzbox_upload_certificate/pull/22

**Comment by cxxcoder** [comment]
No, does not work. The output of

	openssl pkey -in privkey.pem -noout -text | sed -n 1p

for my private key is:

Private-Key: (2048 bit, 2 primes)

**Comment by cxxcoder** [comment]
openssl rsa -in privkey.pem -check -noout

prints `RSA key ok` with exit code 0 for an RSA key and `Not an RSA key` and exit code 1 for an EC key. Thus

	if ! ${OPENSSL_CMD} rsa -in "${privkey}" -check -noout &>/dev/null ; then
	  error "FRITZ!OS only supports RSA private keys."
	fi

should do it.

**Comment by franzs** [comment]
@cxxcoder Thanks a lot. Your check is more elegant.
