### ISSUE TITLE
does not work with 7.57

### ISSUE THREAD

**Issue by chipmunk2000** [franzs/fritzbox_upload_certificate#4]
change the code  between the hashes  to make it work
# generate our upload request
boundary="---------------------------$(date +%Y%m%d%H%M%S)"

cat <<EOD >> ${request_file}
--${boundary}
Content-Disposition: form-data; name="sid"

${sid}
--${boundary}
Content-Disposition: form-data; name="BoxCertPassword"

cert password if needed
--${boundary}
Content-Disposition: form-data; name="BoxCertImportFile"; filename="BoxCert.pem"
Content-Type: application/octet-stream

${certbundle}
--${boundary}--
EOD

# upload the certificate to the box

**Comment by franzs** [comment]
@chipmunk2000 Thanks for reporting this issue.

After having a look at uploading a certificate to a FritzBox with 7.57 I changed the regexp for finding the success message.

Please have a look at PR #5 if it works for you.

The change you proposed is unrelated to 7.57. This would be needed if the certificate key is protected by a password.
